# Generated by Django 5.2.9 on 2026-10-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_alter_campaign_options_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('POTION', 'Potion'), ('SCROLL', 'Scroll'), ('RING', 'Ring'), ('AMULET', 'Amulet'), ('WAND', 'Wand'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('VERY_RARE', 'Very Rare'), ('LEGENDARY', 'Legendary'), ('ARTIFACT', 'Artifact')], default='COMMON', max_length=20)),
                ('description', models.TextField()),
                ('damage', models.CharField(blank=True, max_length=60, null=True)),
                ('protection', models.CharField(blank=True, max_length=60, null=True)),
                ('effect', models.CharField(blank=True, max_length=60, null=True)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('WEAPON', 'Weapon'), ('ARMOR', 'Armor'), ('POTION', 'Potion'), ('SCROLL', 'Scroll'), ('RING', 'Ring'), ('AMULET', 'Amulet'), ('WAND', 'Wand'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('VERY_RARE', 'Very Rare'), ('LEGENDARY', 'Legendary'), ('ARTIFACT', 'Artifact')], max_length=20)),
                ('description', models.TextField()),
                ('damage', models.CharField(blank=True, max_length=60, null=True)),
                ('protection', models.CharField(blank=True, max_length=60, null=True)),
                ('effect', models.CharField(blank=True, max_length=60, null=True)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign')),
                ('base_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_items', to='items.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
