# Generated by Django 5.2.9 on 2026-10-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
