# Generated by Django 5.2.9 on 2026-10-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_options_campaign_created_at_and_more'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaigns.campaign'),
            preserve_default=False,
        ),
    ]
