# Generated by Django 5.2.9 on 2026-10-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_campaigns_character_campaign'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='characters', to='items.campaignitem'),
        ),
    ]
