# Generated by Django 5.2.9 on 2026-10-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_alter_campaign_options_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('reward_description', models.TextField()),
                ('difficulty_rating', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('DEADLY', 'Deadly')], max_length=10)),
                ('level_recommendation', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CampaignQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('reward_description', models.TextField()),
                ('difficulty_rating', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('DEADLY', 'Deadly')], max_length=10)),
                ('level_recommendation', models.CharField(max_length=60)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='campaigns.campaign')),
                ('base_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_quests', to='quests.quest')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
