# Generated by Django 5.2.9 on 2026-10-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_alter_campaign_options_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('ABERRATION', 'Aberration'), ('BEAST', 'Beast'), ('CELESTIAL', 'Celestial'), ('CONSTRUCT', 'Construct'), ('DRAGON', 'Dragon'), ('ELEMENTAL', 'Elemental'), ('FEY', 'Fey'), ('FIEND', 'Fiend'), ('GIANT', 'Giant'), ('HUMANOID', 'Humanoid'), ('MONSTROSITY', 'Monstrosity'), ('PLANT', 'Plant'), ('UNDEAD', 'Undead')], max_length=33)),
                ('alignment', models.CharField(choices=[('LAWFUL_GOOD', 'Lawful Good'), ('NEUTRAL_GOOD', 'Neutral Good'), ('CHAOTIC_GOOD', 'Chaotic Good'), ('LAWFUL_NEUTRAL', 'Lawful Neutral'), ('TRUE_NEUTRAL', 'Neutral'), ('CHAOTIC_NEUTRAL', 'Chaotic Neutral'), ('LAWFUL_EVIL', 'Lawful Evil'), ('NEUTRAL_EVIL', 'Neutral Evil'), ('CHAOTIC_EVIL', 'Chaotic Evil'), ('UNALIGNED', 'Unaligned')], default='UNALIGNED', max_length=55)),
                ('challenge_rating', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('DEADLY', 'Deadly')], max_length=35)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('abilities', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('ABERRATION', 'Aberration'), ('BEAST', 'Beast'), ('CELESTIAL', 'Celestial'), ('CONSTRUCT', 'Construct'), ('DRAGON', 'Dragon'), ('ELEMENTAL', 'Elemental'), ('FEY', 'Fey'), ('FIEND', 'Fiend'), ('GIANT', 'Giant'), ('HUMANOID', 'Humanoid'), ('MONSTROSITY', 'Monstrosity'), ('PLANT', 'Plant'), ('UNDEAD', 'Undead')], max_length=33)),
                ('alignment', models.CharField(choices=[('LAWFUL_GOOD', 'Lawful Good'), ('NEUTRAL_GOOD', 'Neutral Good'), ('CHAOTIC_GOOD', 'Chaotic Good'), ('LAWFUL_NEUTRAL', 'Lawful Neutral'), ('TRUE_NEUTRAL', 'Neutral'), ('CHAOTIC_NEUTRAL', 'Chaotic Neutral'), ('LAWFUL_EVIL', 'Lawful Evil'), ('NEUTRAL_EVIL', 'Neutral Evil'), ('CHAOTIC_EVIL', 'Chaotic Evil'), ('UNALIGNED', 'Unaligned')], default='UNALIGNED', max_length=55)),
                ('challenge_rating', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('DEADLY', 'Deadly')], max_length=35)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('abilities', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='campaigns.campaign')),
                ('base_monster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_monsters', to='monsters.monster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
