# Generated by Django 5.2.9 on 2026-10-01 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_campaign_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
