# Generated by Django 5.2.9 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Cantrip"),
                            (1, "1st level"),
                            (2, "2nd level"),
                            (3, "3rd level"),
                            (4, "4th level"),
                            (5, "5th level"),
                            (6, "6th level"),
                            (7, "7th level"),
                            (8, "8th level"),
                            (9, "9th level"),
                        ],
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("ABJ", "Abjuration"),
                            ("CON", "Conjuration"),
                            ("DIV", "Divination"),
                            ("ENC", "Enchantment"),
                            ("EVO", "Evocation"),
                            ("ILL", "Illusion"),
                            ("NEC", "Necromancy"),
                            ("TRA", "Transmutation"),
                        ],
                        max_length=78,
                    ),
                ),
                ("concentration_required", models.BooleanField()),
                ("cast_as_ritual", models.BooleanField()),
                ("cast_time", models.CharField(max_length=66)),
                ("spell_range", models.CharField(max_length=50)),
                ("spell_duration", models.CharField(max_length=55)),
                (
                    "saving_throw",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("damage", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "allowed_classes",
                    models.ManyToManyField(
                        related_name="allowed_spells", to="characters.characterclass"
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
    ]
